<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <AssemblyTitle>GeoTuner_mod</AssemblyTitle>

  </PropertyGroup>

  <PropertyGroup>
    <Title>GeoTuner all in one 调谐仪(多合一)</Title>
    <Description>Multiple tuners for a single geyser merged into one. (间歇泉协调多合一)</Description>
	  <UsesPLib>true</UsesPLib>
	  <UseCommons>true</UseCommons>


  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Export\README.md" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
</Project>